### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by joego2124** [evaera/RbxSync#30]
This does not work. It is not easy to use at all. The installation process is vague and directions are generalized.
I run the exe, reopen explorer, select a script, press plug-in button, only thing that happens is it switches to the script tool bar in studio. Nothing else happens.
.lua extentions are set to be open with atom.

**Comment by evaera** [comment]
I'm sorry you're having problems using my project, it was never my intention to cause frustration. The reason the directions are general is because it's supposed to be simple and "just work".

The script toolbar shouldn't appear when you open a script because it doesn't open in the Studio editor. When you click the "Open with Editor" button, it should just immediately open the script in your system editor. 

Did you check the output for any hints of what might be wrong?
